plugins {
    id 'java'
}

group = 'ru.alfabank.epk.reactive'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

task runXsdUI(type: JavaExec) {
    main = 'ru.alfabank.epk.reactive.ui.xsd_comparator.UiMain'
    classpath = sourceSets.main.runtimeClasspath
}

task runXpathUI(type: JavaExec) {
    main = 'ru.alfabank.epk.reactive.ui.xpath_comparator.UiMainOnlyXPath'
    classpath = sourceSets.main.runtimeClasspath
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'com.github.ramalapure:xml-parser:1.0'
    implementation 'org.apache.xmlbeans:xmlbeans:5.3.0'

    implementation 'org.swinglabs.swingx:swingx-core:1.6.5-1'

    implementation 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}

test {
    useJUnitPlatform()
}